theme = "ashokai"

[editor]
line-number = "relative"
bufferline = "always"
true-color = true
cursorline = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
# normal = "block"
# select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control"]
right = ["diagnostics", "selections", "file-name", "read-only-indicator", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "󰰒 Normal"
mode.insert = "󰗧 Insert"
mode.select = "󰇀 Select"

[keys.normal]
"C-q" = ":qa!"
# "C-w" = ":bc"
"esc" = ["collapse_selection",  "keep_primary_selection"]
"C-v" = ":vsplit-new"
"C-h" = ":hsplit-new"
"C-e" = ":tree-sitter-scopes"
"C-j" = "add_newline_below"
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-k" = "add_newline_above"


# ~/.config/helix/config.toml
[keys.normal.C-y]
# Open the file(s) in the current window
y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
# Open the file(s) in a vertical pane
v = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh vsplit"
# Open the file(s) in a horizontal pane
h = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh hsplit"

"C-t" = ":set-language ruby"
