# theme = "catppuccin_frappe"
theme = "ashokai_urple"
# theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"
true-color = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
# normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"# Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control"]
# center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "󰰒 Normal"
mode.insert = "󰗧 Insert"
mode.select = "󰇀 Select"

[keys.normal]
"A-up" = "move_line_up"
"A-down" = "move_line_down"
"C-q" = ":qa!"
"C-w" = ":bc"
"esc" = ["collapse_selection",  "keep_primary_selection"]
"C-v" = ":vsplit-new"
"C-h" = ":hsplit-new"
"C-e" = ":tree-sitter-scopes"
"C-j" = "add_newline_below"

"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# "C-S-j" = "add_newline_below"
"C-k" = "add_newline_above"
