
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[language-server.emmet-ls]
args = ["--stdio"]
command = "emmet-ls"

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls", "emmet-ls"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls" ]
formatter = { command = "prettier", args = ["--parser", "javascript"] }
auto-format = true

# OLD CONFIG

# [language-server]
# [language-server.ruby-lsp]
# command = "ruby-lsp" 
# args = ["--debug"] 

# [[language]]
# name = "ruby"
# language-servers = [ { name = "ruby-lsp", only-features = ["format", "diagnostics"]}, {name = "solargraph", except-features = ["format", "diagnostics"]}]
# auto-format = true
# formatter = { command = "standardrb", args = ["--fix"] }

# [[language]]
# name = "erb"
# language-servers = [ { name = "ruby-lsp", only-features = ["format", "diagnostics"]}, {name = "solargraph", except-features = ["format", "diagnostics"]}, "emmet-ls", "tailwindcss-ls"]
# auto-format = true


[language-server.ruby-lsp]
command = "ruby-lsp"

[[language]]
name = "ruby"
language-servers = ["ruby-lsp", "solargraph"]
auto-format = true
formatter = {command = "rufo", args = ["--simple-exit"]}

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/opt/homebrew/lib/node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls", "tailwindcss-ls" , "emmet-ls" ]

# https://www.reddit.com/r/HelixEditor/comments/17kizxs/vue3_usage/

[[language]]
name = "vue"
auto-format = true
scope = "scope.vue"
injection-regex = "vue"
file-types = ["vue"]
language-servers = ["volar", "eslint", "emmet-ls"]
formatter = {command = 'prettier', args = ["--parser", "vue"]}

