# Ashoka Purple theme for Helix
name = "Ashokai Urple"
author = "Your Name"
version = "0.1.0"

# Syntax highlighting
"type" = "purple"
"constant" = "magenta"
"constant.numeric" = "magenta"
"constant.character.escape" = "orange"
"string" = "orange"
"string.regexp" = "blue"
"comment" = "#565775"
"variable" = "yellow"
"class" = {fg ="purple", modifiers = ["bold"]}
"variable.builtin" = "blue"
"variable.parameter" = "yellow"
"variable.other.member" = "fg0"
"label" = "purple"
"punctuation" = "grey2"
"punctuation.delimiter" = "lightblue"
"punctuation.bracket" = "blue2"
"keyword" = "blue"
"keyword.directive" = "aqua"
"operator" = "lightblue"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "aqua"
"tag" = "magenta"
"namespace" = "aqua"
"attribute" = "green"
"constructor" = "purple"
"module" = "blue"
"special" = "orange"
"variable.instance_variable" = "magenta"

# Markup
"markup.heading.marker" = "grey2"
"markup.heading.1" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.2" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg0", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "magenta"
"markup.quote" = "grey2"
"markup.raw" = "green"

# Diff
"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

# UI elements
"ui.background" = { bg = "bg0" }
"ui.background.separator" = "grey0"
"ui.cursor" = { fg = "bg0", bg = "fg0" }
"ui.cursor.match" = { fg = "orange", bg = "bg_visual_yellow" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey2" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.selection" = { bg = "bg3" }
"ui.linenr" = "#5D5E72"
"ui.linenr.selected" = "#7262a6E"
"ui.statusline" = { fg = "fg0", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg0" }
"ui.statusline.normal" = { fg = "bg0", bg = "fg0", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "pink", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey0", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg0", bg = "bg3", modifiers = ["bold"] }
"ui.popup" = { fg = "grey2", bg = "bg2" }
"ui.window" = { fg = "grey0", bg = "bg0" }
"ui.help" = { fg = "fg0", bg = "bg2" }
"ui.text" = "fg0"
"ui.text.focus" = "fg0"
"ui.menu" = { fg = "fg0", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.ruler" = { bg = "bg3" }

# Diagnostics
"hint" = "blue"
"info" = "aqua"
"warning" = "yellow"
"error" = "red"
"diagnostic" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.info" = { underline = { color = "aqua", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]
bg0 = "#211D2A"
bg1 = "#322750"
bg2 = "#49385d"
bg3 = "#4B3E64"
fg0 = "#EFEAFF"
grey0 = "#70697D"
grey2 = "#667E99"
red = "#FF5D5D"
yellow = "#FBC664"
green = "#7AEA92"
blue = "#7AC3FF"
orange = "#FF9647"
purple = "#9983d7"
magenta = "#F94786"
aqua = "#5DB1B1"
pink = "#EA7AD5"

lightblue = "#B0DDD2"
blue2 = "#4E6A97"
